"""Pydantic v2 schemas for the identity module (Task 12.3).

All request / response models used by router.py and cross-module DTOs
exposed through api.py. No SQLAlchemy or FastAPI imports here.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, field_validator

from app.platform.db.enums import AccountStatus, ResidencyProofType, Role


def _upper(value: object) -> object:
    """Upper-case a raw string before enum coercion.

    Role members are declared upper-case, and the endpoints have always accepted
    a case-insensitive spelling. Normalising in a ``mode="before"`` validator keeps
    that behaviour while letting the field itself be typed as the enum, so the
    OpenAPI document publishes a named ``Role`` schema instead of a bare string.
    """
    return value.upper() if isinstance(value, str) else value


# ── Request schemas ────────────────────────────────────────────────────────


class RegistrationRequest(BaseModel):
    """Payload for candidate or senior self-registration."""

    role: str = Field(..., description="CANDIDATE or SENIOR")
    email: EmailStr
    password: str = Field(..., min_length=1)
    full_name: str = Field(..., min_length=1, max_length=100)
    language_preference: str = Field(default="ar", min_length=2, max_length=5)
    residency_proof_type: ResidencyProofType = Field(
        ..., description="MobilePhone, NationalId, or Address"
    )
    residency_proof_value: str = Field(..., min_length=1, max_length=1000)
    # Token generated by an admin via POST /admin/registration-links
    link_token: str = Field(..., min_length=1)

    @field_validator("role")
    @classmethod
    def validate_role(cls, v: str) -> str:
        v_upper = v.upper()
        if v_upper not in ("CANDIDATE", "SENIOR"):
            raise ValueError("role must be CANDIDATE or SENIOR")
        return v_upper

    @field_validator("language_preference")
    @classmethod
    def validate_language(cls, v: str) -> str:
        allowed = {"ar", "he", "en"}
        if v.lower() not in allowed:
            raise ValueError(f"language_preference must be one of {sorted(allowed)}")
        return v.lower()


class VerifyCodeRequest(BaseModel):
    """Submit the 6-digit email verification code."""

    account_id: UUID
    code: str = Field(..., min_length=6, max_length=6, pattern=r"^\d{6}$")


class ResendCodeRequest(BaseModel):
    """Request a new verification code email."""

    account_id: UUID


class LoginRequest(BaseModel):
    """Authenticate an account and receive a token pair."""

    email: EmailStr
    password: str = Field(..., min_length=1)
    role: Role = Field(..., description="ADMIN, CANDIDATE, or SENIOR")
    mfa_code: str | None = Field(default=None, min_length=6, max_length=6)

    @field_validator("role", mode="before")
    @classmethod
    def normalize_role(cls, v: object) -> object:
        return _upper(v)


class RefreshRequest(BaseModel):
    """Exchange a refresh token for a new token pair."""

    refresh_token: str = Field(..., min_length=1)


class SwitchContextRequest(BaseModel):
    """Switch the active role context for a dual-role account."""

    context: str = Field(..., description="CANDIDATE or SENIOR")

    @field_validator("context")
    @classmethod
    def validate_context(cls, v: str) -> str:
        v_upper = v.upper()
        if v_upper not in ("CANDIDATE", "SENIOR"):
            raise ValueError("context must be CANDIDATE or SENIOR")
        return v_upper


class AdminApproveRequest(BaseModel):
    """Admin approval; fast_track skips the meeting step."""

    fast_track: bool = False


class AdminRejectRequest(BaseModel):
    """Admin rejection with a mandatory reason."""

    reason: str = Field(..., min_length=1, max_length=500)


class AdminSuspendRequest(BaseModel):
    """Admin suspension with a mandatory reason."""

    reason: str = Field(..., min_length=1, max_length=500)


class AdminDeactivateRequest(BaseModel):
    """Admin deactivation with a mandatory reason."""

    reason: str = Field(..., min_length=1, max_length=500)


class AdminRoleUpdateRequest(BaseModel):
    """Replace the full role set of an account."""

    roles: list[Role] = Field(..., min_length=1)

    @field_validator("roles", mode="before")
    @classmethod
    def normalize_roles(cls, v: object) -> object:
        return [_upper(role) for role in v] if isinstance(v, list) else v


class CreateRegistrationLinkRequest(BaseModel):
    """Admin creation of a new registration link."""

    role: str = Field(..., description="CANDIDATE or SENIOR")

    @field_validator("role")
    @classmethod
    def validate_role(cls, v: str) -> str:
        v_upper = v.upper()
        if v_upper not in ("CANDIDATE", "SENIOR"):
            raise ValueError("role must be CANDIDATE or SENIOR")
        return v_upper


# ── Response / DTO schemas ─────────────────────────────────────────────────


class AccountDTO(BaseModel):
    """Public representation of an account. Never contains password or secrets."""

    id: UUID
    email: str
    roles: list[Role]
    status: AccountStatus
    language_preference: str
    created_at: datetime
    mfa_enrolled: bool


class RegistrationLinkDTO(BaseModel):
    """Registration link metadata.

    ``token`` is only populated at creation time (POST /admin/registration-links).
    Subsequent fetches (GET /registration-links/{token}) never re-expose it.
    """

    id: UUID
    role: Role
    expires_at: datetime
    # Raw token returned once at creation; None for fetch/validate responses.
    token: str | None = None


class TokenResponse(BaseModel):
    """OAuth2-style token response."""

    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    expires_in: int


class MfaEnrolmentDTO(BaseModel):
    """Data returned when starting MFA enrolment."""

    provisioning_uri: str
    qr_code_png_b64: str


class StatusNoticeDTO(BaseModel):
    """Minimal status information for non-Approved accounts."""

    status: AccountStatus
    next_step: str | None = None


class NotificationTarget(BaseModel):
    """Cross-module DTO used by IdentityApi.list_admin_recipients()."""

    account_id: UUID
    email: str
    language_preference: str


class ListAccountsQuery(BaseModel):
    """Query parameters for GET /admin/accounts."""

    status: str | None = None
    role: str | None = None
    after_id: UUID | None = None
    limit: int = Field(default=20, ge=1, le=100)
