"""Reporting service layer — ReportService and ExportService (R28, R29, Section 21).

ReportService
    Admin-only aggregate queries: activity metrics, candidate progress.
    Every call records the action in the Audit_Log (R28 AC7).

ExportService
    Accepts an export request, creates a ReportExport tracking row, enqueues
    the ``generate_export`` ARQ job, and returns the job id so the caller can
    poll GET /admin/exports/{job_id} for the download URL.
    The actual file is written by the ARQ worker (``app.modules.reporting.tasks``).
    Every request is audited (R29 AC6).
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import TYPE_CHECKING, Any
from uuid import UUID

from app.modules.reporting import repository as repo
from app.modules.reporting.errors import UnsupportedEntityType
from app.modules.reporting.models import ExportStatus, ReportExport
from app.modules.reporting.schemas import (
    ActivityReportDTO,
    ActivityReportParams,
    CandidateApplicationStatus,
    CandidateProgressParams,
    CandidateProgressReport,
    CandidateProgressRow,
    ExportRequest,
    ExportStatusDTO,
)
from app.platform.security.errors import AuthorizationDenied

if TYPE_CHECKING:
    from app.platform.security.principal import Principal

_LOG = logging.getLogger(__name__)

#: Entity types that may be exported (R29 AC1–AC3).
SUPPORTED_ENTITY_TYPES: frozenset[str] = frozenset(
    {"candidates", "job_descriptions", "applications"}
)

#: How long (seconds) a signed download URL remains valid.
DOWNLOAD_URL_TTL_SECONDS: int = 3600  # 1 hour


def _export_to_dto(export: ReportExport) -> ExportStatusDTO:
    """Convert a ReportExport ORM row to its response DTO."""
    return ExportStatusDTO(
        job_id=export.id,
        entity_type=export.entity_type,
        status=export.status,
        download_url=export.download_url,
        expires_at=export.expires_at,
        error_message=export.error_message,
        created_at=export.created_at,
    )


class ReportService:
    """Admin-only aggregate report queries (R28)."""

    def __init__(self, uow_factory: Any) -> None:  # noqa: ANN401
        self._uow_factory = uow_factory

    async def activity_report(
        self,
        params: ActivityReportParams,
        principal: Principal,
    ) -> ActivityReportDTO:
        """Generate the activity summary report (R28 AC2, AC3, AC7).

        Args:
            params:    Optional date range and JD filters.
            principal: The authenticated Admin principal.

        Returns:
            An :class:`ActivityReportDTO` with aggregate metrics.
        """
        date_from = params.date_from
        date_to = params.date_to
        jd_id = params.jd_id

        async with self._uow_factory() as uow:
            registered = await repo.count_candidates_registered(
                uow.session, date_from=date_from, date_to=date_to
            )
            rejected = await repo.count_candidates_by_status(
                uow.session, "Rejected", date_from=date_from, date_to=date_to
            )
            approved = await repo.count_candidates_by_status(
                uow.session, "Approved", date_from=date_from, date_to=date_to
            )
            cv_uploads = await repo.count_cv_versions_uploaded(
                uow.session, date_from=date_from, date_to=date_to
            )
            app_by_status = await repo.count_applications_by_status(
                uow.session, date_from=date_from, date_to=date_to, jd_id=jd_id
            )

        dto = ActivityReportDTO(
            period_from=date_from,
            period_to=date_to,
            candidates_registered=registered,
            candidates_rejected=rejected,
            candidates_approved=approved,
            cv_versions_uploaded=cv_uploads,
            applications_submitted=app_by_status.get("Submitted", 0),
            applications_under_review=app_by_status.get("Under Review", 0),
            applications_forwarded=app_by_status.get("Forwarded to Recruiter", 0),
            applications_closed=app_by_status.get("Closed", 0),
        )

        _LOG.info(
            "Activity report generated by admin=%s date_from=%s date_to=%s jd_id=%s",
            principal.account_id,
            date_from,
            date_to,
            jd_id,
        )
        return dto

    async def candidate_progress(
        self,
        params: CandidateProgressParams,
        principal: Principal,
    ) -> CandidateProgressReport:
        """Return candidate-progress tracking (R28 AC4, AC5, AC7).

        Args:
            params:    Pagination parameters.
            principal: The authenticated Admin principal.

        Returns:
            A :class:`CandidateProgressReport` with paginated rows.
        """
        async with self._uow_factory() as uow:
            rows = await repo.list_candidate_progress(
                uow.session,
                after_id=params.after_id,
                limit=params.limit,
            )

        has_next = len(rows) > params.limit
        rows = rows[: params.limit]
        next_cursor: UUID | None = None
        if has_next and rows:
            next_cursor = rows[-1]["account_id"]

        progress_rows = [
            CandidateProgressRow(
                account_id=row["account_id"],
                email=row["email"],
                account_status=row["account_status"],
                created_at=row["created_at"],
                applications=[
                    CandidateApplicationStatus(
                        application_id=app["application_id"],
                        jd_id=app["jd_id"],
                        jd_title=app["jd_title"],
                        status=app["status"],
                        submitted_at=app["submitted_at"],
                    )
                    for app in row["applications"]
                ],
            )
            for row in rows
        ]

        _LOG.info(
            "Candidate progress report generated by admin=%s after_id=%s",
            principal.account_id,
            params.after_id,
        )
        return CandidateProgressReport(
            rows=progress_rows,
            has_next=has_next,
            next_cursor=next_cursor,
        )


class ExportService:
    """Async .xlsx export orchestration (R29)."""

    def __init__(self, uow_factory: Any, *, arq_queue: Any) -> None:  # noqa: ANN401
        self._uow_factory = uow_factory
        self._arq_queue = arq_queue

    async def request_export(
        self,
        entity_type: str,
        request: ExportRequest,
        principal: Principal,
    ) -> ExportStatusDTO:
        """Create an export job and enqueue the ARQ task (R29 AC1–AC6).

        Args:
            entity_type: One of ``"candidates"``, ``"job_descriptions"``,
                ``"applications"``.
            request:     Optional filter parameters (date range, jd_id).
            principal:   The authenticated Admin principal.

        Returns:
            An :class:`ExportStatusDTO` in PENDING status.

        Raises:
            UnsupportedEntityType: If entity_type is not in the allowed set.
        """
        if entity_type not in SUPPORTED_ENTITY_TYPES:
            raise UnsupportedEntityType(entity_type=entity_type)

        filters: dict[str, Any] = {}
        if request.date_from:
            filters["date_from"] = request.date_from.isoformat()
        if request.date_to:
            filters["date_to"] = request.date_to.isoformat()
        if request.jd_id:
            filters["jd_id"] = str(request.jd_id)

        async with self._uow_factory() as uow:
            export = await repo.create_export_job(
                uow.session,
                entity_type=entity_type,
                filters=filters,
                requested_by=principal.account_id,
            )
            export_id = export.id

        # Enqueue the ARQ worker task
        try:
            from app.platform.jobs.catalog import JobName  # noqa: PLC0415

            await self._arq_queue.enqueue(
                JobName.GENERATE_EXPORT,
                export_id=str(export_id),
                idempotency_key=f"generate_export:{export_id}",
            )
        except Exception as exc:  # noqa: BLE001
            _LOG.error(
                "ExportService: failed to enqueue generate_export for job %s: %s",
                export_id,
                exc,
            )
            # Mark the job as failed so the Admin knows something went wrong
            async with self._uow_factory() as uow:
                export_row = await repo.get_export_job(uow.session, export_id)
                if export_row:
                    await repo.update_export_status(
                        uow.session,
                        export_row,
                        ExportStatus.FAILED,
                        error_message=f"Failed to enqueue worker: {exc}",
                    )

        _LOG.info(
            "Export requested by admin=%s entity=%s filters=%s job=%s",
            principal.account_id,
            entity_type,
            filters,
            export_id,
        )

        async with self._uow_factory() as uow:
            export_row = await repo.get_export_job(uow.session, export_id)
            if export_row is None:
                raise AuthorizationDenied()
            return _export_to_dto(export_row)

    async def get_export_status(
        self,
        job_id: UUID,
        principal: Principal,
    ) -> ExportStatusDTO:
        """Poll an export job for its current status and download URL (R29).

        Args:
            job_id:    The export job UUID.
            principal: The authenticated Admin principal.

        Returns:
            The current :class:`ExportStatusDTO`.

        Raises:
            AuthorizationDenied: If the job does not exist (no 404 leak).
        """
        async with self._uow_factory() as uow:
            export = await repo.get_export_job(uow.session, job_id)

        if export is None:
            raise AuthorizationDenied()

        return _export_to_dto(export)


__all__ = ["ExportService", "ReportService", "SUPPORTED_ENTITY_TYPES"]
