"""Platform baseline: outbox, notifications, job dead-letters.

Revision ID: 0001_platform_baseline
Revises:
Create Date: 2026-09-15

The first migration. It creates the platform-internal tables that already exist
in code (Sections 5–7) plus the two platform-internal enum types they use
(``outbox_email_state``, ``notification_type``). The 15 *shared domain* enum
types from ``platform/db/enums.py`` (Task 2.2) are intentionally **not** created
here: a native PostgreSQL ``ENUM`` is created the first time a table references
it, so each shared enum is emitted by the first domain migration that uses it
(identity, cvs, jobs, …). Creating them up front would leave orphaned types if a
module's shape changed before it landed.

Hand-authored rather than autogenerated because the CI environment has no live
database to diff against; the table definitions mirror the ORM models in
``app/platform/{mail,notifications,jobs}/models.py`` exactly, including the
partial indexes those models declare in ``__table_args__``.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Alembic identifiers ───────────────────────────────────────────────────────
revision: str = "0001_platform_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Platform-internal enum types (declared with their tables, per the model notes).
_OUTBOX_EMAIL_STATE = postgresql.ENUM(
    "Pending",
    "Sent",
    "Failed",
    name="outbox_email_state",
    create_type=False,
)
_NOTIFICATION_TYPE = postgresql.ENUM(
    "VerificationCodeIssued",
    "RegistrationAwaitingReview",
    "OnboardingMeetingRequired",
    "AccountDecisionRecorded",
    "ApplicationSubmitted",
    "ApplicationStatusChanged",
    "CvIntegrityIssue",
    name="notification_type",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()

    _OUTBOX_EMAIL_STATE.create(bind, checkfirst=True)
    _NOTIFICATION_TYPE.create(bind, checkfirst=True)

    # ── outbox_emails (platform/mail/models.py) ───────────────────────────────
    op.create_table(
        "outbox_emails",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("to_address", sa.String(length=320), nullable=False),
        sa.Column("recipient_account_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("template", sa.String(length=100), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False, server_default="en"),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "state",
            _OUTBOX_EMAIL_STATE,
            nullable=False,
            server_default="Pending",
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "next_attempt_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=True,
        ),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_outbox_emails"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_emails_idempotency_key"),
    )
    op.create_index(
        "idx_outbox_emails_recipient_account_id",
        "outbox_emails",
        ["recipient_account_id"],
    )
    op.create_index(
        "idx_outbox_emails_due",
        "outbox_emails",
        ["next_attempt_at"],
        postgresql_where=sa.text("state = 'Pending'"),
    )
    op.create_index(
        "idx_outbox_emails_state_created_at",
        "outbox_emails",
        ["state", "created_at"],
    )

    # ── notifications (platform/notifications/models.py) ──────────────────────
    op.create_table(
        "notifications",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("recipient_account_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("type", _NOTIFICATION_TYPE, nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "read_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_notifications"),
    )
    op.create_index(
        "idx_notifications_recipient_created_at",
        "notifications",
        ["recipient_account_id", "created_at"],
    )
    op.create_index(
        "idx_notifications_unread",
        "notifications",
        ["recipient_account_id"],
        postgresql_where=sa.text("read_at IS NULL"),
    )

    # ── job_dead_letters (platform/jobs/models.py) ────────────────────────────
    op.create_table(
        "job_dead_letters",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("job_id", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("error_type", sa.String(length=200), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column(
            "first_failed_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "last_failed_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "resolved_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=True,
        ),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_job_dead_letters"),
        sa.UniqueConstraint("job_id", name="uq_job_dead_letters_job_id"),
    )
    op.create_index(
        "idx_job_dead_letters_job_name_last_failed_at",
        "job_dead_letters",
        ["job_name", "last_failed_at"],
    )
    op.create_index(
        "idx_job_dead_letters_unresolved",
        "job_dead_letters",
        ["last_failed_at"],
        postgresql_where=sa.text("resolved_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_table("job_dead_letters")
    op.drop_table("notifications")
    op.drop_table("outbox_emails")

    bind = op.get_bind()
    _NOTIFICATION_TYPE.drop(bind, checkfirst=True)
    _OUTBOX_EMAIL_STATE.drop(bind, checkfirst=True)
