"""ARQ worker settings factory.

``platform`` must never import a domain module, and the task handlers live in
the modules that own them, so the worker *entrypoint* is assembled one layer up
(``app/worker.py``) where importing both is legitimate. This module supplies the
reusable half: Valkey settings, lifecycle hooks, and the settings class ARQ's CLI
consumes.

Retries are driven by :mod:`app.platform.jobs.registry`, not by ARQ's own
cadence; the worker's ``max_tries`` is therefore set to the registry ceiling so
our per-task policy is always the binding one.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from app.platform.jobs.queue import ArqTaskQueue
from app.platform.jobs.registry import MAX_WORKER_TRIES, arq_functions
from app.platform.jobs.runtime import configure_worker_runtime, reset_worker_runtime
from app.platform.jobs.scheduler import LeaderElectedScheduler, LeaderLock

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    from arq.connections import RedisSettings
    from arq.worker import Function
    from sqlalchemy.ext.asyncio import AsyncSession

    from app.platform.jobs.catalog import Schedule

    SessionFactory = Callable[[], AsyncSession]

_LOG = logging.getLogger(__name__)

SCHEDULER_CONTEXT_KEY = "scheduler"


def redis_settings(valkey_url: str) -> RedisSettings:
    """Build ARQ Valkey settings from a DSN."""
    from arq.connections import RedisSettings  # noqa: PLC0415

    return RedisSettings.from_dsn(valkey_url)


def build_worker_settings(
    *,
    valkey_url: str,
    session_factory: SessionFactory,
    functions: Sequence[Function] | None = None,
    schedules: Sequence[Schedule] | None = None,
    enable_scheduler: bool = True,
    max_jobs: int = 10,
    job_timeout_seconds: int = 300,
    keep_result_seconds: int = 3600,
    health_check_interval_seconds: int = 30,
) -> type:
    """Build the settings class ARQ's CLI loads.

    Args:
        valkey_url: Valkey/Redis DSN for the queue.
        session_factory: Opens a database session for a job. Injected rather than
            imported so this module keeps no dependency on how sessions are built.
        functions: ARQ functions to serve. Defaults to everything registered at
            call time, so the caller must import its task modules first.
        schedules: Cron schedules to drive. Defaults to the full catalog.
        enable_scheduler: Set ``False`` for a queue-only replica (useful when
            scaling drain capacity without touching scheduling).

    Returns:
        A class suitable for ``arq app.worker.WorkerSettings``.
    """
    resolved_functions = list(functions) if functions is not None else arq_functions()

    async def on_startup(ctx: dict[str, Any]) -> None:
        queue = ArqTaskQueue(ctx["redis"])
        configure_worker_runtime(session_factory=session_factory, queue=queue)
        if not enable_scheduler:
            _LOG.info("Worker started with scheduling disabled")
            return
        scheduler = LeaderElectedScheduler(
            queue=queue,
            lock=LeaderLock(ctx["redis"]),
            **({"schedules": schedules} if schedules is not None else {}),
        )
        await scheduler.start()
        ctx[SCHEDULER_CONTEXT_KEY] = scheduler

    async def on_shutdown(ctx: dict[str, Any]) -> None:
        scheduler = ctx.pop(SCHEDULER_CONTEXT_KEY, None)
        if isinstance(scheduler, LeaderElectedScheduler):
            await scheduler.stop()
        reset_worker_runtime()

    return type(
        "WorkerSettings",
        (),
        {
            "__doc__": "ARQ worker settings (generated by build_worker_settings).",
            "functions": resolved_functions,
            "redis_settings": redis_settings(valkey_url),
            "on_startup": staticmethod(on_startup),
            "on_shutdown": staticmethod(on_shutdown),
            "max_tries": MAX_WORKER_TRIES,
            "max_jobs": max_jobs,
            "job_timeout": job_timeout_seconds,
            "keep_result": keep_result_seconds,
            "health_check_interval": health_check_interval_seconds,
            # Jobs are idempotent on a natural key, so a mid-flight restart may
            # safely re-run them rather than losing them.
            "retry_jobs": True,
        },
    )
