import fc from 'fast-check'
import { describe, expect, it } from 'vitest'

import {
  REFRESH_LEAD_MS,
  REFRESH_LEAD_SECONDS,
  computeRefreshAtEpochMs,
  computeRefreshDelayMs,
  computeRefreshTiming,
  isRefreshDue,
  refreshDeadlineEpochMs,
} from './refresh'

/**
 * ## How the property is read
 *
 * Design Property 4 states: *for any* Access_Token whose `exp` claim is in the
 * future, the computed refresh time is no later than `exp − 60s` and no earlier
 * than the current instant.
 *
 * Taken literally over *every* future `exp`, the two bounds are unsatisfiable:
 * when `exp` is less than 60 seconds away, `exp − 60s` is already in the past,
 * so no instant can be both `≤ exp − 60s` and `≥ now`. The "future `exp`" the
 * requirement is about is therefore an `exp` that still leaves room for the
 * 60-second lead — `exp > now + 60s` — and that is the domain the biconditional
 * below is asserted over.
 *
 * The degenerate remainder (fewer than 60 seconds of life left, or already
 * expired) is asserted separately against the documented resolution in
 * `computeRefreshTiming`: the schedule clamps toward `now` and reports
 * `due: true`, because an immediate exchange is the only action that can still
 * keep the session alive. Both branches are generated by the single property
 * below, so neither half of the input space goes unchecked.
 */

/** A plausible clock reading, in epoch seconds: 2024-01-01 through 2035-01-01. */
const nowEpochSeconds: fc.Arbitrary<number> = fc.integer({
  min: Math.trunc(Date.UTC(2024, 0, 1) / 1000),
  max: Math.trunc(Date.UTC(2035, 0, 1) / 1000),
})

/**
 * The sub-second part of the clock reading. `0` makes `now` land exactly on a
 * second boundary, which is what lets the generator hit the exact `exp − 60s`
 * instant; a non-zero jitter models a reading taken mid-second.
 */
const jitterMs: fc.Arbitrary<number> = fc.oneof(
  { weight: 2, arbitrary: fc.constant(0) },
  { weight: 3, arbitrary: fc.integer({ min: 1, max: 999 }) },
)

/** A clock reading in epoch milliseconds, on and off second boundaries. */
const nowEpochMs: fc.Arbitrary<number> = fc
  .tuple(nowEpochSeconds, jitterMs)
  .map(([seconds, jitter]) => seconds * 1000 + jitter)

/**
 * How much life the token has *beyond* the 60-second lead, in seconds — from
 * zero (the exact deadline) through a century ahead.
 */
const slackSeconds: fc.Arbitrary<number> = fc.oneof(
  { weight: 3, arbitrary: fc.constant(0) },
  { weight: 2, arbitrary: fc.integer({ min: 1, max: 59 }) },
  { weight: 2, arbitrary: fc.integer({ min: 60, max: 3_600 }) },
  { weight: 2, arbitrary: fc.integer({ min: 3_600, max: 86_400 }) },
  { weight: 1, arbitrary: fc.integer({ min: 86_400, max: 31_536_000 }) },
  { weight: 1, arbitrary: fc.integer({ min: 31_536_000, max: 3_153_600_000 }) },
)

/** How far *past* the `exp − 60s` deadline the clock already is, in seconds. */
const deficitSeconds: fc.Arbitrary<number> = fc.oneof(
  { weight: 3, arbitrary: fc.integer({ min: 1, max: 59 }) },
  { weight: 2, arbitrary: fc.integer({ min: 60, max: 61 }) },
  { weight: 2, arbitrary: fc.integer({ min: 62, max: 86_400 }) },
  { weight: 1, arbitrary: fc.integer({ min: 86_401, max: 31_536_000 }) },
)

interface Scenario {
  /** The `exp` claim, as the JWT NumericDate it is: integer epoch seconds. */
  readonly exp: number
  readonly nowEpochMs: number
  /** True when `exp` leaves room for the full 60-second lead (`exp − 60s ≥ now`). */
  readonly leadFits: boolean
}

/**
 * A token with enough life left for the lead: `exp` is rounded *up* to the next
 * whole second so that `exp − 60s` never falls before a mid-second reading, and
 * the `slack = 0, jitter = 0` corner puts `now` exactly on `exp − 60s`.
 */
const leadFitsScenario: fc.Arbitrary<Scenario> = fc
  .tuple(nowEpochMs, slackSeconds)
  .map(([now, slack]) => ({
    exp: Math.ceil(now / 1000) + REFRESH_LEAD_SECONDS + slack,
    nowEpochMs: now,
    leadFits: true,
  }))

/**
 * A token handed over inside its lead window — fewer than 60 seconds of life
 * left, or already expired. `exp` stays positive so it remains a usable
 * NumericDate rather than a rejected input.
 */
const leadExceededScenario: fc.Arbitrary<Scenario> = fc
  .tuple(nowEpochMs, deficitSeconds)
  .map(([now, deficit]) => ({
    exp: Math.max(1, Math.floor(now / 1000) + REFRESH_LEAD_SECONDS - deficit),
    nowEpochMs: now,
    leadFits: false,
  }))

const scenario: fc.Arbitrary<Scenario> = fc.oneof(
  { weight: 3, arbitrary: leadFitsScenario },
  { weight: 1, arbitrary: leadExceededScenario },
)

describe('refresh scheduling properties', () => {
  // Feature: frontend-web-application, Property 4: Refresh is scheduled at least
  // 60 seconds before expiry — For any Access_Token whose `exp` claim is in the
  // future, the Session_Manager's computed refresh time is no later than
  // `exp − 60s` and no earlier than the current instant.
  //
  // **Validates: Requirements 4.4**
  it('schedules the exchange no later than exp − 60s and no earlier than now', () => {
    fc.assert(
      fc.property(scenario, ({ exp, nowEpochMs: now, leadFits }) => {
        const expiryEpochMs = exp * 1000
        const deadlineEpochMs = expiryEpochMs - REFRESH_LEAD_MS
        const timing = computeRefreshTiming(exp, now)

        // A well-formed NumericDate and a finite clock reading always schedule.
        expect(timing).not.toBeNull()
        if (timing === null) {
          return
        }

        // The deadline is the requirement's 60-second lead, nothing else.
        expect(timing.deadlineEpochMs).toBe(deadlineEpochMs)
        expect(timing.deadlineEpochMs).toBe(refreshDeadlineEpochMs(exp))

        // Invariants that hold across the whole input space.
        expect(timing.atEpochMs).toBeGreaterThanOrEqual(now)
        expect(timing.delayMs).toBe(timing.atEpochMs - now)
        expect(timing.delayMs).toBeGreaterThanOrEqual(0)
        expect(timing.due).toBe(now >= deadlineEpochMs)
        expect(timing.due).toBe(isRefreshDue(exp, now))
        expect(timing.expired).toBe(now >= expiryEpochMs)

        // The projections agree with the full timing.
        expect(computeRefreshAtEpochMs(exp, now)).toBe(timing.atEpochMs)
        expect(computeRefreshDelayMs(exp, now)).toBe(timing.delayMs)

        if (leadFits) {
          // Property 4 proper: both bounds hold simultaneously, so the exchange
          // starts at least the full 60 seconds before the token expires.
          expect(timing.atEpochMs).toBeLessThanOrEqual(deadlineEpochMs)
          expect(expiryEpochMs - timing.atEpochMs).toBeGreaterThanOrEqual(REFRESH_LEAD_MS)
          expect(timing.expired).toBe(false)

          // Strictly before the deadline the schedule is the deadline itself and
          // the timer is armed for the future; exactly on it, it is due now.
          if (now < deadlineEpochMs) {
            expect(timing.atEpochMs).toBe(deadlineEpochMs)
            expect(timing.delayMs).toBe(deadlineEpochMs - now)
            expect(timing.delayMs).toBeGreaterThan(0)
            expect(timing.due).toBe(false)
          } else {
            expect(now).toBe(deadlineEpochMs)
            expect(timing.atEpochMs).toBe(now)
            expect(timing.delayMs).toBe(0)
            expect(timing.due).toBe(true)
          }
        } else {
          // Degenerate half: the deadline is already past, so the bounds are
          // resolved toward `now` and the exchange is due immediately.
          expect(deadlineEpochMs).toBeLessThanOrEqual(now)
          expect(timing.atEpochMs).toBe(now)
          expect(timing.delayMs).toBe(0)
          expect(timing.due).toBe(true)
        }
      }),
      { numRuns: 500 },
    )
  })
})
