"""ORM models for the tamper-evident audit log (R8, Task 9.1).

Design references: design.md § "Audit Log Design", Data Models §audit_log /
§audit_actor_identities.

Key invariants enforced here:
* ``audit_actor_identities`` is the identity snapshot store, anonymisable on
  deletion requests without touching hash-chained ``audit_log`` rows.
* ``audit_log`` is RANGE-partitioned by ``occurred_at`` (monthly) so the 7-year
  table stays manageable.  The application-computed hash chain spans partitions.
* The database role is granted INSERT + SELECT only.  A BEFORE UPDATE OR DELETE
  trigger also rejects mutations — enforced both in the DB and in the migration.
* ``id`` is a ``BIGSERIAL`` because the chain walk is sequential and integer PKs
  are substantially cheaper to scan sequentially over 7 years than UUIDs.

Partitioning note
-----------------
SQLAlchemy's declarative mapper does not natively model PostgreSQL declarative
partitioning; the ``__table_args__`` ``postgresql_partition_by`` argument
instructs Alembic's autogenerate to emit the correct DDL.  Partition child tables
are created by the migration and by a monthly ARQ job — they are not ORM models.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
import uuid

from sqlalchemy import (
    BigInteger,
    Boolean,
    Index,
    LargeBinary,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.platform.db.base import Base, UtcTimestampMs, utc_now

# ── audit_actor_identities ─────────────────────────────────────────────────────

class AuditActorIdentity(Base):
    """Snapshot of an actor's identity at the time of each audit entry.

    Separated from ``audit_log`` so that a Candidate deletion request can
    anonymise the personal fields (name, email) without touching the
    hash-chained rows.  One row per (account_id, role, display_name) triple;
    the ``system`` sentinel has a hard-coded zero UUID (R8 AC7).

    Columns
    -------
    id          UUID PK (generated by app, not DB gen_random_uuid so tests can
                create the sentinel row predictably).
    account_id  UUID of the account, NULL for the ``system`` sentinel.
    role        The actor's active role at capture time (free-text, so future
                roles don't require a migration).
    display_name  Human-readable snapshot: "Karim Haddad (Admin)" etc.
    email       Email snapshot at capture time.  Nulled out on anonymisation.
    is_system   True only for the sentinel row (account_id == zero UUID).
    anonymised_at  Set when a deletion request removes personal fields.
    """

    __tablename__ = "audit_actor_identities"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    account_id: Mapped[uuid.UUID | None] = mapped_column(
        nullable=True,
        index=True,
    )
    role: Mapped[str] = mapped_column(String(50), nullable=False)
    display_name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    is_system: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    anonymised_at: Mapped[datetime | None] = mapped_column(
        UtcTimestampMs, nullable=True, default=None
    )

    # Reverse relationship — viewonly, no FK constraint required on the
    # partitioned child table.  Only used in admin tooling, never in write paths.
    entries: Mapped[list[AuditLogEntry]] = relationship(
        "AuditLogEntry",
        primaryjoin="AuditActorIdentity.id == foreign(AuditLogEntry.actor_identity_id)",
        lazy="noload",
        viewonly=True,
    )

    __table_args__ = (
        UniqueConstraint(
            "account_id",
            "role",
            name="uq_audit_actor_identities_account_id_role",
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<AuditActorIdentity {self.display_name!r} role={self.role!r}>"


# ── Sentinel UUID — zero UUID reserved for the ``system`` actor ──────────────
SYSTEM_ACTOR_UUID: uuid.UUID = uuid.UUID("00000000-0000-0000-0000-000000000000")


# ── audit_log ─────────────────────────────────────────────────────────────────

class AuditLogEntry(Base):
    """One immutable record of an entity mutation or authorization denial (R8).

    The table is RANGE-partitioned by ``occurred_at`` (monthly); child
    partitions are created by the migration and by the ``create_audit_partition``
    ARQ job so they always exist one month ahead.

    Columns
    -------
    id              BIGSERIAL — sequential, cheap for chain-walk scans.
    occurred_at     UTC ms-precision timestamp — the partition key.
    actor_identity_id  FK → audit_actor_identities.  Never NULL; system
                    operations use the sentinel row.
    action          Stable verb string, e.g. ``account.status_changed``,
                    ``cv_version.uploaded``, ``auth.denied``.
    entity_type     Pascal-case entity name, e.g. ``Account``, ``CvVersion``.
    entity_id       String representation of the entity PK (UUID or bigint).
    before          JSONB map of changed columns *before* the mutation.
                    NULL for INSERT (no prior state) and auth-denial entries.
    after           JSONB map of changed columns *after* the mutation.
                    NULL for DELETE and auth-denial entries.
    reason          Free text supplied by the actor (e.g. rejection reason).
    request_id      Propagated from ``request.state.request_id`` middleware.
    outcome         ``"success"`` or ``"failure"``; failure entries are written
                    on a separate connection to survive the rollback.
    error_type      Set on failure entries: the exception class name.
    prev_hash       SHA-256 of the previous entry's ``entry_hash`` (bytea).
                    NULL for the very first entry (genesis).
    entry_hash      SHA-256( canonical_json(entry_sans_hashes) || prev_hash ).
                    Computed by the application before INSERT.
    """

    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
    )
    occurred_at: Mapped[datetime] = mapped_column(
        UtcTimestampMs,
        nullable=False,
        default=utc_now,
    )

    actor_identity_id: Mapped[uuid.UUID] = mapped_column(
        # Declared as a plain column (no FK object) because the parent table is
        # not partitioned and the FK still works.  We use a string-based FK so
        # that future declarative partitioning helpers don't complain.
        nullable=False,
        index=True,
    )

    action: Mapped[str] = mapped_column(String(200), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(100), nullable=False)
    entity_id: Mapped[str] = mapped_column(String(200), nullable=False)

    before: Mapped[dict[str, Any] | None] = mapped_column(nullable=True)
    after: Mapped[dict[str, Any] | None] = mapped_column(nullable=True)

    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    request_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    outcome: Mapped[str] = mapped_column(
        String(20), nullable=False, default="success"
    )
    error_type: Mapped[str | None] = mapped_column(String(200), nullable=True)

    prev_hash: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    entry_hash: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)

    # ORM relationship — viewonly, no FK constraint on the partitioned table.
    # Loaded only when explicitly requested (lazy="noload" means never auto-loaded).
    actor_identity: Mapped[AuditActorIdentity] = relationship(
        "AuditActorIdentity",
        primaryjoin="foreign(AuditLogEntry.actor_identity_id) == AuditActorIdentity.id",
        lazy="noload",
        viewonly=True,
    )

    __table_args__ = (
        # Primary query pattern: look up history of one entity (R8 AC4).
        Index(
            "idx_audit_log_entity_type_entity_id_occurred_at",
            "entity_type",
            "entity_id",
            "occurred_at",
        ),
        # Secondary patterns: filter by actor or by action (R8 AC4).
        Index(
            "idx_audit_log_actor_identity_id_occurred_at",
            "actor_identity_id",
            "occurred_at",
        ),
        Index(
            "idx_audit_log_action_occurred_at",
            "action",
            "occurred_at",
        ),
        # BRIN index on occurred_at for the 7-year range scan.  Much smaller
        # than a B-tree on a monotonically-increasing column.
        Index(
            "idx_audit_log_occurred_at_brin",
            "occurred_at",
            postgresql_using="brin",
        ),
        # Partitioning declaration — consumed by Alembic's autogenerate and by
        # any tool that reflects the schema.
        {
            "postgresql_partition_by": "RANGE (occurred_at)",
        },
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<AuditLogEntry id={self.id} action={self.action!r}"
            f" entity={self.entity_type}/{self.entity_id}>"
        )


__all__ = [
    "SYSTEM_ACTOR_UUID",
    "AuditActorIdentity",
    "AuditLogEntry",
]
